### ISSUE TITLE
vsync error

### ISSUE THREAD

**Issue by Muhammed-Hayr-Ali** [lucastssb/new-instagram#1]
_animController = AnimationController(vsync: this);

vsync error

**Comment by lucastssb** [comment]
Hello, it seem that this error only happens when you are using the stable version of flutter.

Run flutter clean e restart your IDE to fix it.

Here's some references: 
- https://github.com/flutter/flutter/issues/62574
- https://github.com/flutter/flutter/issues/63486
- https://github.com/flutter/flutter/issues/63088
